
# filter table data before export to CSV file
csv_export_filters:
  APP_NAVIGATION    : 'app_id = 765'
  APP_APPLICATIONS  : 'app_id = 765'
  APP_CONTEXTS      : 'app_id = 765'
  APP_SETTINGS      : 'app_id = 765'
  APP_LOVS          : 'app_id = 765'
  APP_ROLES         : 'app_id = 765'

# auto add and lock new object with the prefix
auto_lock_add_prefix : 'TRP'

# auto filter object names (to reduce subset of fetched objects significantly)
auto_filter_prefix   : 'TRP'

# auto refresh and auto add CSV files
auto_csv_refresh  : False
auto_csv_add      : ['APP_LOV%']

