prompt --application/pages/page_00100
begin
--   Manifest
--     PAGE: 00100
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.7'
,p_default_workspace_id=>1000000000000
,p_default_application_id=>765
,p_default_id_offset=>0
,p_default_owner=>'APPS'
);
wwv_flow_imp_page.create_page(
 p_id=>100
,p_name=>'Trips Planning'
,p_alias=>'HOME'
,p_step_title=>'Trips Planning'
,p_autocomplete_on_off=>'OFF'
,p_group_id=>wwv_flow_imp.id(115360446004041100)  -- PAGE GROUP: 1) Trips
,p_page_css_classes=>'MULTICOLUMN'
,p_page_template_options=>'#DEFAULT#'
,p_required_role=>wwv_flow_imp.id(107669254908639002)  -- AUTHORIZATION: IS_USER
,p_protection_level=>'C'
,p_page_component_map=>'23'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(35707257718708515)
,p_plug_name=>'Trips for &P100_YEAR.'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(29310834936377326)
,p_plug_display_sequence=>10
,p_location=>null
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(35707364103708516)
,p_plug_name=>'TABS'
,p_region_name=>'YEARS'
,p_region_css_classes=>'TABS'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(29277583231377259)
,p_plug_display_sequence=>20
,p_location=>null
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(59736969471540239)
,p_plug_name=>'[MAP]'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="margin-top: 2rem;"'
,p_plug_template=>wwv_flow_imp.id(29277583231377259)
,p_plug_display_sequence=>40
,p_location=>null
,p_lazy_loading=>true
,p_plug_source_type=>'NATIVE_MAP_REGION'
,p_plug_display_condition_type=>'ITEM_IS_NOT_NULL'
,p_plug_display_when_condition=>'P100_YEAR'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_map_region(
 p_id=>wwv_flow_imp.id(39829993255471721)
,p_region_id=>wwv_flow_imp.id(59736969471540239)
,p_height=>640
,p_tilelayer_type=>'CUSTOM'
,p_tilelayer_name_default=>'osm-positron'
,p_navigation_bar_type=>'SMALL'
,p_navigation_bar_position=>'END'
,p_init_position_zoom_type=>'STATIC'
,p_init_position_from_browser=>false
,p_init_position_lon_static=>'14.4939'
,p_init_position_lat_static=>'50.1272'
,p_init_zoomlevel_static=>'2'
,p_layer_messages_position=>'BELOW'
,p_show_legend=>false
,p_features=>'MOUSEWHEEL_ZOOM:RECTANGLE_ZOOM:SCALE_BAR:INFINITE_MAP:BROWSER_LOCATION:CIRCLE_TOOL:DISTANCE_TOOL'
);
wwv_flow_imp_page.create_map_region_layer(
 p_id=>wwv_flow_imp.id(39830465514471722)
,p_map_region_id=>wwv_flow_imp.id(39829993255471721)
,p_name=>'PAST_EVENTS'
,p_layer_type=>'POINT'
,p_display_sequence=>10
,p_location=>'LOCAL'
,p_query_type=>'TABLE'
,p_table_name=>'TRP_TRIPS_MAP_V'
,p_where_clause=>'is_future IS NULL'
,p_include_rowid_column=>false
,p_items_to_submit=>'P100_YEAR'
,p_has_spatial_index=>false
,p_pk_column=>'TRIP_ID'
,p_geometry_column_data_type=>'LONLAT_COLUMNS'
,p_longitude_column=>'GPS_LONG'
,p_latitude_column=>'GPS_LAT'
,p_stroke_color=>'#000000'
,p_fill_color=>'&COLOR.'
,p_point_display_type=>'SVG'
,p_point_svg_shape=>'Default'
,p_point_svg_shape_scale=>'1.5'
,p_feature_clustering=>false
,p_tooltip_adv_formatting=>false
,p_link_target_type=>'REDIRECT_PAGE'
,p_link_target=>'f?p=&APP_ID.:150:&SESSION.::&DEBUG.:150:P150_TRIP_ID:&TRIP_ID.'
,p_display_in_legend=>false
);
wwv_flow_imp_page.create_map_region_layer(
 p_id=>wwv_flow_imp.id(39831085504471723)
,p_map_region_id=>wwv_flow_imp.id(39829993255471721)
,p_name=>'FUTURE_EVENTS'
,p_layer_type=>'POINT'
,p_display_sequence=>20
,p_location=>'LOCAL'
,p_query_type=>'TABLE'
,p_table_name=>'TRP_TRIPS_MAP_V'
,p_where_clause=>'is_future = ''Y'''
,p_include_rowid_column=>false
,p_items_to_submit=>'P100_YEAR'
,p_has_spatial_index=>false
,p_pk_column=>'TRIP_ID'
,p_geometry_column_data_type=>'LONLAT_COLUMNS'
,p_longitude_column=>'GPS_LONG'
,p_latitude_column=>'GPS_LAT'
,p_stroke_color=>'#000000'
,p_fill_color=>'&COLOR.'
,p_point_display_type=>'SVG'
,p_point_svg_shape=>'Default'
,p_point_svg_shape_scale=>'1.5'
,p_feature_clustering=>false
,p_tooltip_adv_formatting=>false
,p_link_target_type=>'REDIRECT_PAGE'
,p_link_target=>'f?p=&APP_ID.:150:&SESSION.::&DEBUG.:150:P150_TRIP_ID:&TRIP_ID.'
,p_display_in_legend=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(97459382867484584)
,p_plug_name=>'[CARDS]'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(29284659758377272)
,p_plug_display_sequence=>30
,p_query_type=>'TABLE'
,p_query_table=>'TRP_TRIPS_GRID_V'
,p_include_rowid_column=>false
,p_lazy_loading=>true
,p_plug_source_type=>'NATIVE_CARDS'
,p_ajax_items_to_submit=>'P100_YEAR'
,p_plug_query_num_rows_type=>'SCROLL'
,p_show_total_row_count=>false
,p_plug_display_condition_type=>'ITEM_IS_NOT_NULL'
,p_plug_display_when_condition=>'P100_YEAR'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_card(
 p_id=>wwv_flow_imp.id(39828579895470967)
,p_region_id=>wwv_flow_imp.id(97459382867484584)
,p_layout_type=>'GRID'
,p_grid_column_count=>5
,p_title_adv_formatting=>false
,p_title_column_name=>'TRIP_NAME'
,p_sub_title_adv_formatting=>true
,p_sub_title_html_expr=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<span class="a-CardView-subTitle">&TRIP_SUBHEADER.</span>',
'<br /><br />'))
,p_body_adv_formatting=>false
,p_second_body_adv_formatting=>false
,p_badge_column_name=>'BADGE_DAYS'
,p_badge_css_classes=>'&BADGE_CLASS.'
,p_media_adv_formatting=>false
,p_pk1_column_name=>'OLD_TRIP_ID'
);
wwv_flow_imp_page.create_card_action(
 p_id=>wwv_flow_imp.id(39829008385470968)
,p_card_id=>wwv_flow_imp.id(39828579895470967)
,p_action_type=>'FULL_CARD'
,p_display_sequence=>10
,p_link_target_type=>'REDIRECT_PAGE'
,p_link_target=>'f?p=&APP_ID.:150:&SESSION.::&DEBUG.:150:P150_TRIP_ID:&TRIP_ID.'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(39828078235469608)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(35707257718708515)
,p_button_name=>'ADD_TRIP'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--iconLeft'
,p_button_template_id=>wwv_flow_imp.id(29418815222377556)
,p_button_image_alt=>'Add Trip'
,p_button_position=>'RIGHT_OF_TITLE'
,p_button_redirect_url=>'f?p=&APP_ID.:105:&SESSION.::&DEBUG.:105::'
,p_icon_css_classes=>'fa-plus'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(35707421900708517)
,p_name=>'P100_YEAR'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(35707364103708516)
,p_prompt=>'Year'
,p_display_as=>'NATIVE_RADIOGROUP'
,p_named_lov=>'TRP_YEARS'
,p_field_template=>wwv_flow_imp.id(29415985826377548)
,p_item_css_classes=>'TABS'
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs:t-Form-fieldContainer--radioButtonGroup'
,p_is_persistent=>'U'
,p_lov_display_extra=>'NO'
,p_attribute_01=>'100'
,p_attribute_02=>'SUBMIT'
,p_attribute_03=>'N'
);
wwv_flow_imp.component_end;
end;
/
